name: Run Python Script

on:
  push:
    branches:
      - main  # Trigger on push to the main branch
  workflow_dispatch:  # Allows manual triggering

jobs:
  run-script:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner

    steps:
    # Step 1: Check out the repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Step 2: Debugging - Print current directory
    - name: Print current directory
      run: pwd

    # Step 3: Debugging - List all files in the repository
    - name: List files in root directory
      run: ls -al

    # Step 4: Debugging - List files in NCRTracker/Code directory
    - name: List files in NCRTracker directory
      run: ls -al NCRTracker || echo "Directory not found"

    # Step 5: Run the Python script
    - name: Run Python Script
      run: python Code.py
